application:  inspired-muse-95702
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: mealonline_templates_withinput.app

libraries:
- name: jinja2
  version: latest
